### ISSUE TITLE
Toggling theme options with select boxes in Chrome

### ISSUE THREAD

**Issue by dstrojny** [thethemefoundry/struts#3]
When I toggle Theme Option areas that contain select boxes I get weird stripes showing up on the screen. See below.

http://cl.ly/2A2g3i1I3k2x2x1Y362W

Chrome version: 18.0.1025.151

**Comment by andyadams** [comment]
Reopening this. Instead of modifying the styles, we'll just remove the slideToggle (assuming the slide is what is causing this display issue).

**Comment by andyadams** [comment]
Whoops, shoulda changed the revert message

**Comment by andyadams** [comment]
I don't think this is an issue any more since we remove slideToggle. Closing.
