### ISSUE TITLE
Localization string name change

### ISSUE THREAD

**Issue by lukemcdonald** [thethemefoundry/struts#7]
When implementing the framework into a theme, you need to go through and change the `struts`localization string name to the name of the theme. I was thinking it would be helpful to change this string to `struts-i18n` or something a bit out of the ordinary to make it easy to do a global search and replace.

Thoughts?

**Comment by dstrojny** [comment]
Hey again Luke. As mentioned in the pull request, this is going to have to wait till next month, but I promise we will take a look at it and respond. Sorry for the slow feedback cycle :(
